markdown:
  options:
    auto_ids: false

generation:
  day_archives: false

date_formats:
  month: '%B %Y'

output:
  posts: 'interviews'

layouts:
  posts: 'interviews'
  category: 'interviews'
  year: 'interviews'
  month: 'interviews'